name: Website Mirror
on: 
  issues:
    types: [opened]
jobs:
    build:
        name: Setup Environment for Mirroring
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./
               env:
                  URL: ${{ secrets.getac.webflow.io}}
                  _GITHUB_TOKEN: ${{ secrets.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 }}
                  USER_NAME: ${{ secrets.kkarnesdesigns }}
                  USER_EMAIL: ${{ secrets.kyle@kkarnesdesigns.com }}
